t_unlink: t_unlink.c ../../lib/error_functions.c ../../lib/get_num.c
	gcc  -Wall -Wextra -std=gnu99 -pedantic -Wmissing-prototypes \
	-Wstrict-prototypes -Wold-style-definition \
	t_unlink.c ../../lib/error_functions.c ../../lib/get_num.c \
	-o t_unlink
