t_stat: t_stat.c file_perms.c ../../../lib/error_functions.c
	gcc  -Wall -Wextra -std=gnu99 -pedantic -Wmissing-prototypes \
         -Wstrict-prototypes -Wold-style-definition \
         t_stat.c file_perms.c ../../../lib/error_functions.c \
         -o t_stat
