xattr_view: xattr_view.c ../../../lib/error_functions.c
	gcc  -Wall -Wextra -std=gnu99 -pedantic -Wmissing-prototypes \
	-Wstrict-prototypes -Wold-style-definition \
	xattr_view.c ../../../lib/error_functions.c \
	-o xattr_view;
