12-1: 12-1.c ../../../../lib/error_functions.c ../../../../users_groups/ugid_functions-c/ugid_functions.c
	gcc 12-1.c ../../../../lib/error_functions.c \
	    ../../../../users_groups/ugid_functions-c/ugid_functions.c \
		-o 12-1
