12-3: 12-3.c ../../../../lib/error_functions.c 
	gcc  -Wall -Wextra -std=gnu99 -pedantic -Wmissing-prototypes -Wstrict-prototypes \
		-Wold-style-definition \
	12-3.c ../../../../lib/error_functions.c \
		-o 12-3
