t_mount: t_mount.c ../../lib/error_functions.c
	gcc  -Wall -Wextra -std=gnu99 -pedantic -Wmissing-prototypes -Wstrict-prototypes \
		-Wold-style-definition \
	t_mount.c ../../lib/error_functions.c -o t_mount
