list_files: list_files.c ../../../lib/error_functions.c 
	gcc  -Wall -Wextra -std=gnu99 -pedantic -Wmissing-prototypes \
	-Wstrict-prototypes -Wold-style-definition \
	list_files.c ../../../lib/error_functions.c \
	-o list_files
