build: t_umask.c ../../t_stat/c-t_stat/file_perms.c ../../../lib/error_functions.c
	gcc  -Wall -Wextra -std=gnu99 -pedantic -Wmissing-prototypes \
         -Wstrict-prototypes -Wold-style-definition \
        t_umask.c ../../t_stat/c-t_stat/file_perms.c ../../../lib/error_functions.c \
	-o t_umask
