build: t_chown.c ../../../users_groups/ugid_functions-c/ugid_functions.c ../../../lib/error_functions.c
	gcc -Wall -Wextra -std=gnu99 -pedantic -Wmissing-prototypes \
	-Wstrict-prototypes -Wold-style-definition \
	t_chown.c ../../../users_groups/ugid_functions-c/ugid_functions.c ../../../lib/error_functions.c \
	-o t_chown