t_dirbasename: t_dirbasename.c ../../lib/error_functions.c 
	gcc  -Wall -Wextra -std=gnu99 -pedantic -Wmissing-prototypes \
	-Wstrict-prototypes -Wold-style-definition \
	t_dirbasename.c ../../lib/error_functions.c \
	-o t_dirbasename
