demo_inotify: demo_inotify.c ../../../lib/error_functions.c 
	gcc  -Wall -Wextra -std=gnu99 -pedantic -Wmissing-prototypes \
	-Wstrict-prototypes -Wold-style-definition \
	demo_inotify.c ../../../lib/error_functions.c \
	-o demo_inotify 
